// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This class provides a set of default Firebase options based on the target
/// platform. It simplifies the initialization of Firebase in your Flutter
/// application by automatically selecting the appropriate configuration for
/// the current platform.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] based on the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase options for web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFWOEwuvG4Pm7yMMlG9N_4l1Fl5fOiOpU',
    appId: '1:298476267485:web:9364aa79618490f8c17834',
    messagingSenderId: '298476267485',
    projectId: 'jobdirectapp-b242b',
    authDomain: 'jobdirectapp-b242b.firebaseapp.com',
    storageBucket: 'jobdirectapp-b242b.appspot.com',
  );

  /// Firebase options for Android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29fdav4QS5fbimeA712MWqgPpynXx-Zg',
    appId: '1:298476267485:android:cd63b9e44f7ef34cc17834',
    messagingSenderId: '298476267485',
    projectId: 'jobdirectapp-b242b',
    storageBucket: 'jobdirectapp-b242b.appspot.com',
  );
}
